Implemented gc command.

diff --git a/bin/buster b/bin/buster
--- a/bin/buster
+++ b/bin/buster
@@ -25,6 +25,8 @@ BUSTER_NODE_MODULES_PATH="${BUSTER_DEPS_PATH}/${BUSTER_NODE_MODULES_IDENTIFIER}"
 BUSTER_OUT_PATH="${BUSTER_OUT}/${BUSTER_DEPS_IDENTIFIER}-${BUSTER_NODE_MODULES_IDENTIFIER}"
 BUSTER_COMMAND=$1
 
+PATH="$(dirname ${BUSTER_NODE_PATH}):${PATH}"
+
 # Ensure deps/out and remove tmp if it exists
 mkdir -p ${BUSTER_DEPS_PATH}
 mkdir -p ${BUSTER_OUT_PATH}
@@ -32,33 +34,33 @@ if [ -d "${BUSTER_TMP}" ]; then
   rm -rf ${BUSTER_TMP}
 fi
 
-# Bootstrap node
-if [ ! -f "${BUSTER_NODE_PATH}" ]; then
-  mkdir -p ${BUSTER_TMP}
-  pushd ${BUSTER_TMP} > /dev/null
-  BUSTER_NODE_DOWNLOAD_URL=https://nodejs.org/dist/${BUSTER_NODE_VERSION}/${BUSTER_NODE_IDENTIFIER}.tar.gz
-  if ! wget -q ${BUSTER_NODE_DOWNLOAD_URL}; then
-    echo "Failed to download ${BUSTER_NODE_DOWNLOAD_URL}"
-    exit
+buster_ensureNode() {
+  if [ ! -f "${BUSTER_NODE_PATH}" ]; then
+    mkdir -p ${BUSTER_TMP}
+    pushd ${BUSTER_TMP} > /dev/null
+    BUSTER_NODE_DOWNLOAD_URL=https://nodejs.org/dist/${BUSTER_NODE_VERSION}/${BUSTER_NODE_IDENTIFIER}.tar.gz
+    if ! wget -q ${BUSTER_NODE_DOWNLOAD_URL}; then
+      echo "Failed to download ${BUSTER_NODE_DOWNLOAD_URL}"
+      exit
+    fi
+    tar xzf ${BUSTER_NODE_IDENTIFIER}.tar.gz
+    rm ${BUSTER_NODE_IDENTIFIER}.tar.gz
+    mv ${BUSTER_NODE_IDENTIFIER} node
+    mv node ${BUSTER_DEPS_PATH}
+    popd > /dev/null
+    rm -rf ${BUSTER_TMP}
   fi
-  tar xzf ${BUSTER_NODE_IDENTIFIER}.tar.gz
-  rm ${BUSTER_NODE_IDENTIFIER}.tar.gz
-  mv ${BUSTER_NODE_IDENTIFIER} node
-  mv node ${BUSTER_DEPS_PATH}
-  popd > /dev/null
-  rm -rf ${BUSTER_TMP}
-fi
+}
 
-PATH="$(dirname ${BUSTER_NODE_PATH}):${PATH}"
-
-# Bootstrap node_modules
-if [ ! -d "${BUSTER_NODE_MODULES_PATH}" ]; then
-  mkdir -p ${BUSTER_TMP}
-  cp ${BUSTER_PATH}/package.json ${BUSTER_TMP}
-  ${BUSTER_NODE_BIN}/npm i --prefix ${BUSTER_TMP} > /dev/null
-  mv ${BUSTER_TMP}/node_modules ${BUSTER_NODE_MODULES_PATH}
-  rm -rf ${BUSTER_TMP}
-fi
+buster_ensureNodeModules() {
+  if [ ! -d "${BUSTER_NODE_MODULES_PATH}" ]; then
+    mkdir -p ${BUSTER_TMP}
+    cp ${BUSTER_PATH}/package.json ${BUSTER_TMP}
+    ${BUSTER_NODE_BIN}/npm i --prefix ${BUSTER_TMP} > /dev/null
+    mv ${BUSTER_TMP}/node_modules ${BUSTER_NODE_MODULES_PATH}
+    rm -rf ${BUSTER_TMP}
+  fi
+}
 
 # Compiles ts files from the src folder
 buster_compileSelf() {
@@ -80,6 +82,12 @@ buster_symlinkModules() {
     ${BUSTER_NODE_EXE} $symlinkModules $@
 }
 
+buster_check() {
+  buster_symlinkModules "$@"
+  
+  ${BUSTER_NODE_MODULES_PATH}/.bin/tsc --noEmit $@
+}
+
 buster_init() {
   local init="$(buster_compileSelf "init.ts")"
 
@@ -88,10 +96,17 @@ buster_init() {
   buster_symlinkModules "$@"
 }
 
-buster_check() {
-  buster_symlinkModules "$@"
-  
-  ${BUSTER_NODE_MODULES_PATH}/.bin/tsc --noEmit $@
+buster_gc() {
+  local command="${1:-}"
+
+  case $command in
+    "deps") rm -rf ${BUSTER_DEPS} ;;
+    "out") rm -rf ${BUSTER_OUT} ;;
+    *)
+      rm -rf ${BUSTER_DEPS}
+      rm -rf ${BUSTER_OUT}
+      ;;
+  esac
 }
 
 buster_run() {
@@ -103,9 +118,15 @@ buster_run() {
     ${BUSTER_NODE_EXE} ${importFlag} $@
 }
 
+if [ $BUSTER_COMMAND != "gc" ]; then
+  buster_ensureNode
+  buster_ensureNodeModules
+fi
+
 case $BUSTER_COMMAND in
-  "init") buster_init "${@:2}" ;;
   "check") buster_check "${@:2}" ;;
+  "init") buster_init "${@:2}" ;;
+  "gc") buster_gc "${@:2}" ;;
   "symlinkModules") buster_symlinkModules "${@:2}" ;;
   "run") buster_run "${@:2}" ;;
   *) buster_run "$@" ;;
